config/routes.rb
Rails.application.routes.draw do
  
  resources :empleados
  

  root to: 'empleados#index'
  resources :empleados do  
    get :autocomplete_empleado_num_empleado, :on => :collection
  end 

end

app/models/empleado.rb
class Empleado < ActiveRecord::Base
  validates :num_empleado, :uniqueness => true, length: { maximum: 6 }
  validates_numericality_of :num_empleado, on: :create, :message => "debe ser numerico"
  validates :nom_empleado, presence: true, length: { maximum: 30 }
  validates :ip, presence: true, :uniqueness => true, 
            :format => { :with => Resolv::IPv4::Regex, :message => "Formato no valido"},
            length: { maximum: 16 }
  validates :mac_address, presence: true, :uniqueness => true, length: { maximum: 40 }
  validates :departamento, presence: true, length: { maximum: 60 }

  def self.search(query)
    where("num_empleado like ?", "%#{query}%") 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController
  autocomplete :empleado, :num_empleado

  before_action :set_empleado, only: [:show, :edit, :update, :destroy]
  def index
     #@empleados = Empleado.all.order('ip ASC')
    if params[:search]
      @empleados = Empleado.search(params[:search]).order("ip ASC")
    else
      @empleados = Empleado.all.order('ip ASC')
    end
  end

  def show
    
  end

  def new
    @empleado = Empleado.new
  end

  def create
    @empleado = Empleado.create(empleado_params)

    respond_to do |format|
     if @empleado.save
        format.json { head :no_content}
        format.js
      else
        format.json { render json: @empleado.errors.full_messages,
                             status: :unprocessable_entity }
      end
    end
  end

  def edit
    
  end

  def update
    respond_to do |format|
      if @empleado.update(empleado_params)
        format.json { head :no_content }
        format.js
      else
        format.json { render json: @empleado.errors.full_messages,
                             status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @empleado.destroy
    respond_to do |format|
      format.js
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
  def set_empleado
    @empleado = Empleado.find(params[:id])
  end

  def empleado_params
    params.require(:empleado).permit(:num_empleado, :nom_empleado,
                                    :ip, :mac_address, :departamento)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/search_suggestions_helper.rb
module SearchSuggestionsHelper
end

app/views/empleados/_dialog.html.erb
<div class="modal fade"
           id="dialog" tabindex="-1" role="dialog" 
           aria-labelledby="myModalLabel"
           aria-hidden="true" 
           data-backdrop="static" 
           data-keyboard="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" 
                data-dismiss="modal" 
                aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
        <h3 class="modal-title"></h3>
      </div>
      <div class="modal-body">
      </div>
     
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/empleados/_empleado.html.erb
<tr id="empleado_<%= empleado.id %>">
  <td><%= empleado.num_empleado %></td>
  <td><%= empleado.nom_empleado %></td>
  <td><%= empleado.ip %></td>
  <td><%= empleado.mac_address %></td>
  <td><%= empleado.departamento %></td>
  <td>
    <%= link_to 'Editar', edit_empleado_path(empleado), remote:true, :class => 'btn btn-sm btn-info' %>
    <%= link_to 'Delete', empleado, remote: true, :method => :delete, data: {confirm: "Liberar: #{empleado.nom_empleado} #{empleado.ip}"}, :class => 'btn btn-sm btn-danger' %>
  </td>
</tr>

app/views/empleados/_form.html.erb
<%= form_for(@empleado, remote: true, :html => { :role => "form"}) do |f|  %>
  <div id="error_explanation" class="bg-danger text-danger"></div>

  <div class="row">
    <div class="col-sm-6">
      <div class="form-group">
        <%= f.label :ip, :class => "control-label" %>
        <%= f.text_field :ip, :class => "form-control first_input" %>
      </div>
      <div class="form-group">
        <%= f.label :num_empleado, :class => "control-label" %>
        <%= f.text_field :num_empleado, :maxlength => 6, :class => "form-control" %>
      </div>
       <div class="form-group">
        <%= f.label :nom_empleado, :class => "control-label" %>
        <%= f.text_field :nom_empleado, :class => "form-control" %>
       </div>
  </div>   
    
 
  <div class="col-sm-6">
    <div class="form-group">
      <%= f.label :mac_address, :class => "control-label" %>
      <%= f.text_field :mac_address, :class => "form-control" %>
    </div>
  <div class="form-group">
      <%= f.label :departamento, :class => "control-label" %>
      <%= f.text_field :departamento, :class => "form-control" %>
  </div>
  <div class="form-group">
      <%= f.submit @empleado.new_record? ? "Asignar" : "Modificar", :class => "btn btn-primary" %>
  </div>
    
    </div>
  </div>
<%end%>

app/views/empleados/create.js.erb
$('#dialog').modal('toggle');
$('#empleados').append('<%= j render (@empleado) %>')

app/views/empleados/destroy.js.erb
$('#empleado_<%= @empleado.id %>').fadeOut();

app/views/empleados/edit.js.erb
// Add the dialog title
$('#dialog h3').html("<i class=' glyphicon glyphicon-pencil'></i> Edit Customer");

// Render the edit form
$('.modal-body').html('<%= j render("form") %>');

// Show the dynamic dialog
$('#dialog').modal("show");

// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
    $('.first_input').focus()
  })

app/views/empleados/index.html.erb
<div class="container">
  <h2>Asignar IP</h2>
  <div class="well">
    <%= link_to "Asignar IP", new_empleado_path, remote:true, class: "btn btn-primary" %>
  </div>
  <div class="new-empleado"></div>
  <table id class="table table-bordered table-striped">
    <thead>
      <tr>
        <%= form_tag(empleados_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
         <%= submit_tag "Search", :name => nil %>
       <%end%>
        
        <th>Numero de empleado</th>
        <th>Nombre</th>
        <th>IP</th>
        <th>MAC ADDRESS</th>
        <th>Departamento</th>
      </tr>
    </thead>
    <tbody id="empleados">
      <%= render @empleados %>
    </tbody>
  </table>
  
  <%= render 'dialog' %>

</div>

app/views/empleados/new.js.erb
// Add the dialog title
$('#dialog h3').html("<i class='glyphicon glyphicon-plus'></i> Asignar");
 
// Render the new form
$('.modal-body').html('<%= j render("form") %>');
 
// Show the dynamic dialog
$('#dialog').modal("show");
 
// Set focus to the first element
$('#dialog').on('shown.bs.modal', function () {
    $('.first_input').focus()
  })

app/views/empleados/update.js.erb
$('#dialog').modal('toggle');
$('#empleado_<%= @empleado.id %>').replaceWith('<%= j render (@empleado) %>')

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Consultas</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>